# much of this configuration is based on http://stackoverflow.com/a/30925448/1866171
sudo: false
language: cpp
compiler:
    - clang
    - gcc
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
- cmake . && make
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
script: ./bin/seqscan_test
